### ISSUE TITLE
Customize the Export button

### ISSUE THREAD

**Issue by rghiglianovich** [dabeng/OrgChart#168]
It'd be interesting having an  option to link the "export" event to a custom button ,
something like:

`
 $('#chart-container').orgchart({
.....

  'exportButton': true,

  'exportButtonId': $('#mybutton'),

  'exportFilename': 'MyOrgChart',

  'exportFileextension': 'pdf'

 });
`

**Comment by dabeng** [comment]
Hi @korenanzo , you mean you want to add another option "exportButtonId" which is used to specify the export button by users?

**Comment by korenanzo** [comment]
Yes 

I wish I put the button or a link outside the current org chart space.

With a new option I could create a button everywhere, then tell to orgchart to use it.

RIc
Inviato da iPhone

**Comment by dabeng** [comment]
no question:blush Thanks a lot for your great idea.

**Comment by AWulkan** [comment]
Since this has not yet been implemented I would just want to say to everyone who's reading this that you can hide the normal export button, then create your own an set the "onclick" even to trigger the export function.

Now how do you do this you might ask?

1. hide the normal export button with this css:
```css
.oc-export-btn {
    display: none;
}
```

Then create your button:
```html
<button type="button" class="my-class" onclick="clickExportButton();">Export</button>
```

Then write this function to export it:
```js
function clickExportButton() {
    $(".oc-export-btn").click();
}
```

Now there are better ways to write the code, but I just made that to show you an example. :)

**Comment by dabeng** [comment]
@korenanzo @AWulkan , since version 2.0.5, you guys can call method export() to export orgchat as a picture or a pdf file within your own code snippets. For details, please refer to [export description](https://github.com/dabeng/OrgChart#exportexportfilename-exportfileextension) of methods section.

**Comment by AWulkan** [comment]
@dabeng Good, I guess this issue can be closed then.

**Comment by doarsal** [comment]
http://creappti.com/scripts/orgChart/
