### ISSUE TITLE
reload OrgChart using Ajax

### ISSUE THREAD

**Issue by irsalshabirin** [dabeng/OrgChart#202]
i want to reload my data, and I want to get "listener" when load Ajax has been success or done.
but can you help me ?
thanks

**Comment by dabeng** [comment]
Hi @irsalshabirin , you can get "listener" with success() or done() of jquery ajax API, it's nothing to do with orgchart plugin.

As for reload your data, I'm glad to tell you that you can make use of init() method since version 2.0.0. Hope you like this [Demo](http://dabeng.github.io/OrgChart/reload-data/).
