### ISSUE TITLE
How do I select a node in code

### ISSUE THREAD

**Issue by vmmartinezlona** [dabeng/OrgChart#355]
I want to make a loop to add nodes, but I don't know how to select the parent node

**Comment by warrenspe** [comment]
try: `jQuery("#id-of-your-chart").find(".node:first")`

**Comment by vmmartinezlona** [comment]
and then, how do i select another node? I want to fill in a function, but i don't know how can i select every node

**Comment by warrenspe** [comment]
What exactly are you trying to do?  Typically rather than creating the nodes yourself you do so by passing them through the data argument to the initializer.

That aside, you can use jQuery selectors to access nodes based on their contents, or you can use the root node and [this function](https://github.com/dabeng/OrgChart#getrelatednodesnode-relation) to access nodes iteratively from the root node

**Comment by dabeng** [comment]
Hi @vmmartinezlona. Maybe method getRelatedNodes() can help you.
