### ISSUE TITLE
Hybrid(horizontal + vertical) OrgChart

### ISSUE THREAD

**Issue by Destructrix** [dabeng/OrgChart#61]
I want to have horizontal(direction:'t2b') layout only till 2nd depth of nodes.  After that, i want the succeeding nodes in vertical(direction:'l2r') layout. How to do this ?

**Comment by dabeng** [comment]
Yes, I'm working on this feature. In fact, your demand is similar to this [issue](https://github.com/dabeng/OrgChart/issues/46).

**Comment by Destructrix** [comment]
Thanks for pointing out. i will close this issue and follow up that.

**Comment by dabeng** [comment]
From version 1.2.0, users never have to worry about how to align a huge of nodes in one screen of browser. The option "verticalDepth" allows users to align child nodes vertically from the given depth.
![snapshot](https://cloud.githubusercontent.com/assets/5689075/18310623/181015aa-74c5-11e6-8220-c52e5a5a805f.png)

**Comment by Destructrix** [comment]
Hi @dabeng, Thanks for the help. Truly appreciate your work.

**Comment by WyattEdwardGillette** [comment]
Hi @dabeng,

I want to display the last 3 nodes in React, here is the image
![image](https://user-images.githubusercontent.com/58803185/142611655-c4a2e6fa-f92d-4ddf-8f9a-a1ed4a204c0c.png)

You stated that from only version 1.2.0, verticalDepth can be used to solve this problem. However, I run "npm i @dabeng/react-orgchart verion, and it turns out to be only 1.0.0
![image](https://user-images.githubusercontent.com/58803185/142612050-d595dde3-7e34-40bd-9ac0-f47acd5be512.png)
I tried to update the version, but it is just does not work. Could you please give me some insights for this problem, or suggest me other solutions?

Many thanks!

**Comment by springgrass11** [comment]
Hi @dabeng,
Is there a way to mix the vertical and horizontal different level instead for multi levels?  and within different children?
Thanks!

**Comment by SlimGary** [comment]
> Hi @Destructrix .From version 1.2.0, users never have to worry about how to align a huge of nodes in one screen of browser. The option "verticalDepth" allows users to align child nodes vertically from the given depth. But currently, this option is incompatible with many other options or methods, like direction, drag&drop, addChildren(), removeNodes(), getHierarchy() and so on. These conflicts will be solved one by one in the later versions.

Did you manage to install version 1.2.0 with react ?
