### ISSUE TITLE
Structure table by Title

### ISSUE THREAD

**Issue by SHRIVES23** [dabeng/OrgChart#90]
Is there a way to structure the table by title? For example, because the secretary to the COO reports to him, she appears within the same line as a Vice President that reports to him as well.

**Comment by dabeng** [comment]
sorry @SHRIVES23 , I can't get your point. Could you upload a picture to illustrate your demand.

**Comment by SHRIVES23** [comment]
I don't have a photo at the moment. Basically it's

Level 1 - CEO.
Level 2 - COO
Level 3 - COO secretary, Directors, VP

They don't like that the secretary and directors are on the same level as VP. They'd like it as...
Level 1 - CEO.
Level 2 - COO
Level 3 - VP
Level 4 Director (connected to COO)
Level 5 - Secretary (connected to COO)

I can mock a photo later if it isn't making sense.

**Comment by dabeng** [comment]
Hi @SHRIVES23 , I got your point. I think the secretary node is a disturbance factor in your organization chart. In my opinion, it's also inappropriate to let it be a leaf node, because the upper level node is not the direct leader for the secretary node. On the other hand, if you do that, you will have to construct a complex path connected to COO. So I provide you with a compromise plan -- regard secretary node as affiliated node and place it beside COO node.
![ceo](https://cloud.githubusercontent.com/assets/5689075/19230328/a7041dfe-8e99-11e6-88ac-ea233ac7dc3a.png)

If necessary, you can toggle this affiliated node.
